In [1]:
import pandas as pd
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from pandas.plotting import parallel_coordinates
import plotly.express as px

In [4]:
new_dataset = pd.read_csv('../data/processed/tidy_dataset.csv', ',', encoding='ISO-8859-1')

In [5]:
new_dataset

,Unnamed: 0,n_semesters,sum_credits,GPA,failed_subjects,FACULTAD,NOMBRE_PROGRAMA,Mandatory_subjects_GPA,Optinals_GPA,failed_mandatory,failed_optional,gpa_last_semester,GENERO,EDAD,COLEGIO_PROCEDENCIA,PUNT_TOTAL,PUNT_AREA,ES_DESERTOR
0,0,11,150.0,3.504000,5,FACULTAD DE CIENCIAS ADMINISTRATIVAS Y CONTABLES,ADMINISTRACIÃN DE EMPRESAS,3.51,3.49,5.0,0.0,4.56,M,22.0,COL COOP COOSERVICIOS,438,49,NO
1,1,6,139.0,4.153237,1,FACULTAD DE CIENCIAS ADMINISTRATIVAS Y CONTABLES,ADMINISTRACIÃN DE EMPRESAS,4.15,4.18,1.0,0.0,3.64,M,23.0,INSTITUTO DE EDUCACION MEDIA DIVERSIFICADA INE...,386,48,NO
2,2,10,141.0,4.078723,2,FACULTAD DE CIENCIAS ADMINISTRATIVAS Y CONTABLES,ADMINISTRACIÃN DE EMPRESAS,4.09,4.05,1.0,1.0,5.00,F,22.0,I.E. ANTONIO NARIÃO,460,51,NO
3,3,10,151.0,3.500000,7,FACULTAD DE CIENCIAS ADMINISTRATIVAS Y CONTABLES,ADMINISTRACIÃN DE EMPRESAS,3.50,3.49,4.0,3.0,3.36,F,25.0,I.E. LUIS HERNANDEZ VARGAS,41,42,NO
4,4,10,139.0,4.069784,1,FACULTAD DE CIENCIAS ADMINISTRATIVAS Y CONTABLES,ADMINISTRACIÃN DE EMPRESAS,4.08,4.03,1.0,0.0,3.69,M,25.0,IE TEC JOSE IGNACIO DE MARQUEZ,50,49,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10206,10206,1,17.0,4.288235,0,FACULTAD DE CIENCIAS HUMANAS Y EDUCATIVAS,LICENCIATURA EN PEDAGOGÃA INFANTIL,4.29,NaN,0.0,NaN,4.29,M,21.0,I.E. SAN IGNACIO DE LOYOLA,243,54,NO
10207,10207,3,46.0,3.884783,0,FACULTAD DE CIENCIAS HUMANAS Y EDUCATIVAS,LICENCIATURA EN PEDAGOGÃA INFANTIL,3.88,NaN,0.0,NaN,3.91,F,20.0,I.E. LUIS ENRIQUE BARON LEAL,258,50,NO
10208,10208,3,30.0,3.786667,2,FACULTAD DE CIENCIAS HUMANAS Y EDUCATIVAS,LICENCIATURA EN PEDAGOGÃA INFANTIL,3.79,NaN,2.0,NaN,3.40,F,20.0,INSTITUCIÃN EDUCATIVA ANTONIO RICAURTE,252,50,NO
10209,10209,2,15.0,3.813333,1,FACULTAD DE CIENCIAS HUMANAS Y EDUCATIVAS,LICENCIATURA EN PEDAGOGÃA INFANTIL,3.81,NaN,1.0,NaN,4.47,F,20.0,I.E. DEL LLANO,218,42,NO
10210,10210,1,20.0,3.560000,2,FACULTAD DE CIENCIAS HUMANAS Y EDUCATIVAS,LICENCIATURA EN PEDAGOGÃA INFANTIL,3.56,NaN,2.0,NaN,3.56,F,19.0,COLEGIO ANTONIO NARIÃO,268,50,NO